### ISSUE TITLE
why exact Gemfile for Rails Version

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#1]
in the gem is fixed Rails 4.2.5 this breaks any other combination.
Remove / Change that?

**Comment by florianeck** [comment]
Hi, yeah this is an issue that comes along when trying to use 'rspec-rails' in order to have controller test capabilities. 
in order to have rails testing capabilities with rspec for a plugin (which is actually NOT a classical rails project) i have to include all the gems as they are listed in the host app.

i guess adding a comment to the gemfile and commenting out the gems could help here, as this gem setup is only required for running tests
